modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/N3ROO/AimAssistanceMod/issues"
license="MIT License"

[[mods]]
modId="aimassistancemod"
version="1.2.0"
displayName="Aim Assistance"
updateJSONURL="https://raw.githubusercontent.com/N3ROO/AimAssistanceMod/MC_1.16.2/update.json"
displayURL="https://github.com/N3ROO/AimAssistanceMod/"
# logoFile="examplemod.png"
# credits="someone"
authors="@N3ROO on github"
description='''
A minecraft mod that helps aiming (at mods, blocks, but not players). Made for players using controllers or even disabled players with difficulties to aim.'''